version: "3.8"
services:
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database
    redis:
        image: redis
        ports:
            - "6379:6379"
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        environment: 
            - PORT=8000
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - DATABASE_URL=mysql+pymysql://root:password@mysql:3306/database
        ports:
            - "80:8000"
        depends_on: 
            - redis
            - mysql
    worker:
        build:
            context: ./
            dockerfile: Dockerfile
        command: rq worker --url redis://redis:6379
        environment: 
            - DATABASE_URL=mysql+pymysql://root:password@mysql:3306/database
        depends_on: 
            - redis
            - mysql


        
